#The random module must be imported in order to generate random numbers
import random

#A random number between 1 and 10 will be generated by the random module and stored in the variable named number
number = random.randint(1, 10)

#The player name is defined with a questions that requires user input
player_name = input("Hello, What's your last name?")

#The number of guesses is defined and set at a minimum of zero
number_of_guesses = 0 

#After the user inputs name their name will be displayed with the game statement
print('okay! '+ player_name + ' I am Guessing a number between 1 and 10:')


#Adding a while loop to ensure the minium number of guesses by each user is the starting point and the number of guesses will end at 5 guesses
while number_of_guesses < 5:
    guess = int(input())
    number_of_guesses += 1

#The if statements prints responses whether the user guesses too low or too high
    if guess < number:
        print('Your guess is too low')
    if guess > number:
        print('Your guess is too high')
    if guess == number:
        break
#The if statement prints the total guesses the user made and got the right number
if guess == number:
    print('You guessed the number in ' + str(number_of_guesses) + ' tries!')

#The else statement prints the total guesses the user made and got the right number
else:
     print('You did not guess the number, The number was ' + str(number))


